spring:
  application:
    name: notification-service

server:
  port: 8082

spring.datasource:
  url: jdbc:postgresql://postgres-anal:5432/notifydb
  username: notifyuser
  password: notifypass
  driver-class-name: org.postgresql.Driver

spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  open-in-view: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true