spring:
  application:
    name: analytics-service

server:
  port: 8083

spring.datasource:
  url: jdbc:postgresql://postgres-anal:5432/analdb
  username: analuser
  password: analpass
  driver-class-name: org.postgresql.Driver

spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  open-in-view: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true